const maker = require('mumaker');

module.exports = {
    name: "3dneon",
    description: "Make text logo",
    category: "Textpro",
    start: async(vorterx, m,{pushName,prefix,text, toReact, botName}) => {
        if(!text) { await toReact("⭕"); return m.reply(`*need query ex neon aztec*`);
    }
        await toReact("✔️");
        maker.textpro("https://textpro.me/create-3d-neon-light-text-effect-online-1028.html", [
    `${text}`,]).then((data) => vorterx.sendMessage(m.from, { image: { url: data }, caption: `Generated by ${process.env.BOTNAME}` }, { quoted: m }));
    }
  };
